##########################################
## Ansible tasks for Nginx application configurations during EC2 Init
##########################################



# Validate Nginx service
- name: validated Nginx
  service: 
    name: nginx
    state: started
    enabled: yes
  ignore_errors: yes
  tags:
  - precheck