##########################################
## Ansible tasks for Nginx application configurations during EC2 Init
##########################################

# Copy rpm file from s3
- name: Copy Nginx rpm from s3
  shell: |
    aws cp s3://moe-core-automation-ap-southeast-1/Binary/nginx/nginx-1.18.0-2.el8.ngx.x86_64.rpm /tmp/nginx.rpm
  
# Install nginx offline
- name: Install Nginx local flie
  yum: 
    name: /tmp/nginx.rpm 
    state: present
  when: ansible_os_family == "RedHat"

- name: copy nginx site.conf
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-enabled/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: 
  - Restart nginx

handlers:
  - name: Restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
